name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  git_bot_token:
    description: Git Bot token used to push to protected branches because github token can't
    required: false

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.git_bot_token || github.token }}
        fetch-depth: 0

    # Needed for nx affected command, it set the BASE and HEAD env variables
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    # Set ups the git user for the Changelog commit
    - name: Setup git user to "🤖 NgWorker Bot"
      shell: bash
      run: git config user.email "-" && git config user.name "🤖 NgWorker Bot"

    - name: Determine Node.js version
      id: node_version
      shell: bash
      run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: ${{ steps.node_version.outputs.node_version }}
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable --immutable-cache
