name: Setup

description: Setup Node.js, cache and install dependencies

runs:
  using: composite
  steps:
    # Needed for nx affected command, it set the BASE and HEAD env variables
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - name: Determine Node.js version
      id: node_version
      shell: bash
      run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: ${{ steps.node_version.outputs.node_version }}
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable --immutable-cache
